# Generated by Django 5.0.6 on 2024-05-24 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('grade_or_year', models.CharField(blank=True, max_length=30, null=True)),
                ('current_location', models.CharField(blank=True, max_length=120, null=True)),
                ('subjects', models.CharField(blank=True, choices=[('multiselect_tags', 'multiselect_tags'), ('multiselect_tags2', 'multiselect_tags2')], max_length=510, null=True)),
                ('attendance', models.CharField(blank=True, choices=[('multiselect_tags', 'multiselect_tags'), ('multiselect_tags2', 'multiselect_tags2')], max_length=255, null=True)),
                ('availability', models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekends', 'Weekends'), ('Morning', 'Morning'), ('Afternoons', 'Afternoons'), ('Evenings', 'Evenings')], max_length=510)),
                ('additional_preferences', models.TextField(blank=True, null=True)),
                ('communication_language', models.CharField(choices=[('english', 'english'), ('french', 'french'), ('spanish', 'spanish')], max_length=255)),
                ('short_term_goals', models.TextField(blank=True, null=True)),
                ('long_term_goals', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
